version: '3.3'

services:

  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USERNAME=root
    ports:
      - "3308:3306"

  vis-test:
    image: vis-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - mysql-db
    environment:
      - DBHOST=mysql-db
      - spring.datasource.url=jdbc:mysql://mysql-db-container:3306/public?createDatabaseIfNotExist=true
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.datasource.username=root
      - spring.datasource.password=admin